spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/dark?useUnicode=True&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    host: smtp.163.com
    port: 465
    username: adamboov@163.com
    password: JBJBDNRBGLWWOGMI
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true